baseURL = 'https://blog.tippfehlr.dev'
languageCode = 'en-us'
title = 'tippfehlr’s blog'
theme = 'hello-friend-ng'
paginate = 10
enableGitInfo = true

[params]
dateform = "2006-01-02 15:04"
dateformShort = "2006-01-02"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"

homeSubtitle = "My own little personal blog. My space. Unbelievable, right?"
disableReadOtherPosts = true
enableSharingButtons = false
enableGlobalLanguageMenu = false
gitUrl = "https://github.com/tippfehlr/blog/commit/"
enableThemeToggle = true

description = "tippfehlr's blog"
keywords = "blog, programming"
images = [""]

plausibleDataDomain = "blog.tippfehlr.dev"
plausibleScriptSource = "https://plausible.tippfehlr.dev/js/script.js"

[params.logo]
# logoMark = ">"
# logoCursorPathname = "/img/cursor.svg"
logoCursorDisabled = true
# logoCursorColor = "#000000"
# logoCursorAnimate = true
logoText = "tippfehlr’s blog"
logoHomeLink = "/"

[params.author]
name = "tippfehlr"

[taxonomies]
category = "blog"
tag = "tags"
series = "series"

[[menu.main]]
identifier = "posts"
name = "posts"
url = "/posts"

[[menu.main]]
identifier = "about"
name = "about"
url = "/about"

[params.footer]
# trademark = 2024
rss = true
# copyright = true
# author = true
